"""
Step 02 — Raw Text-to-SQL (From Question to Data)
==================================================

Goal:
    Now we will connect our Mistral LLM to the database schema.
    We will build a simple pipeline:
        1. Extract the DB schema using `db_utils.py`.
        2. Prompt the model with the schema and the user's business question.
        3. Parse the SQL response (cleaning up any Markdown styling).
        4. Execute the SQL directly in DuckDB and display the results.

Run it:
    python 02_raw_text_to_sql.py
"""

import re
import llm_utils as llm
import db_utils

# --- 1. System Prompt for Text-to-SQL ------------------------------------
# We must be very precise in telling the model to return ONLY the raw SQL,
# otherwise it might return conversational filler like "Here is the query:"
# which would crash DuckDB.
SYSTEM_PROMPT = """You are a DuckDB SQL expert. Given the database schema below, write a single valid SQL query that answers the user's question.

Database Schema Context:
{schema_context}

Rules:
1. Return ONLY the raw SQL query. Do not add any conversational text.
2. Do not wrap the SQL query in markdown blocks (e.g., do not use ```sql ... ```).
3. Only use tables and columns defined in the schema.
4. Ensure the query is compatible with DuckDB SQL.
"""


def clean_sql(raw_sql: str) -> str:
    """
    Cleans up the SQL generated by the LLM.
    Even when instructed not to, LLMs frequently wrap code in markdown blocks.
    We use regex to extract the raw code inside any markdown blocks.
    """
    # Remove markdown code block syntax if present
    match = re.search(r"```sql\s+(.*?)\s*```", raw_sql, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    
    # Generic markdown block fallback
    match = re.search(r"```\s+(.*?)\s*```", raw_sql, re.DOTALL)
    if match:
        return match.group(1).strip()
        
    return raw_sql.strip()


def generate_sql(question: str, schema_context: str) -> str:
    """Send the schema and question to Mistral and return the SQL query."""
    model = llm.get_llm(temperature=0.0) # Always use temperature=0 for coding
    
    # Combine system prompt and user question
    prompt = SYSTEM_PROMPT.format(schema_context=schema_context)
    user_message = f"Question: {question}"
    
    # Send messages to the model
    messages = [
        ("system", prompt),
        ("user", user_message)
    ]
    
    response = model.invoke(messages)
    return clean_sql(response.content)


if __name__ == "__main__":
    # 1. Start the DB connection
    print("Initializing DuckDB...")
    try:
        con = db_utils.get_db_connection()
        schema = db_utils.get_database_schema(con)
    except Exception as err:
        print(f"Failed to load database: {err}")
        exit(1)
    
    # 2. Define the business question
    question = "What is the scrap rate of the molding station?"

    print(f"\nUser Question: '{question}'")
    
    # 3. Ask LLM to generate SQL
    print("Generating SQL query using Mistral...")
    sql_query = generate_sql(question, schema)
    print(f"\n--- Generated SQL ---\n{sql_query}\n---------------------")
    
    # 4. Run the query on DuckDB
    print("Running query in DuckDB...")
    try:
        results = con.execute(sql_query).fetchdf() # Fetch as a pandas DataFrame
        print("\n--- Query Results ---")
        print(results)
        print("---------------------")
    except Exception as err:
        print(f"\nDatabase execution failed: {err}")
        
    con.close()

# =========================================================================
# YOUR CHALLENGE (15 min)
# -------------------------------------------------------------------------
# 1. Test the script with a query requiring a table join.
#    Try this question:
#    "What is the average conductor resistance for Premium (PT77) steering wheels?"
#    Does the model successfully identify that it needs to join the
#    `station_conductor` table with another table to filter by product type, 
#    or did it write a query that failed or returned wrong columns?
#
# 2. Few-shot Prompting: Sometimes the model forgets to cast percentages or
#    round values. Add 2 "few-shot examples" (question/SQL pairs) to the 
#    SYSTEM_PROMPT to show the model how to compute scrap rate correctly
#    and how to write DuckDB views. Test if the output quality improves.
# =========================================================================
